import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NavBar } from "../../components/ui/tubelight-navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navItems = [
    { name: "Home", url: "/" },
    { name: "Learning Lounge", url: "/learning-lounge" },
    { name: "What we do", url: "/what-we-do" },
    { name: "Library", url: "/library" },
    { name: "Pricing", url: "/pricing" },
  ];
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`} suppressHydrationWarning>
        <NavBar items={navItems} />
        {children}
      </body>
    </html>
  );
}
