import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "../../components/ui/tubelight-navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navItems = [
    { name: "Home", url: "/" },
    { name: "Learning Lounge", url: "/learning-lounge" },
    { name: "What we do", url: "/what-we-do" },
    { name: "Library", url: "/library" },
    { name: "Pricing", url: "/pricing" },
  ];
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar items={navItems} />
        {children}
      </body>
    </html>
  );
}
